server:
  port: 8082




etv:
  link:
    config:
      port: 8135
      max-idle-time: 600

logging:
  file: classpath:logback.xml

spring:
  application:
    name: etvLink
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
  redis2:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5


